name: 'Ploi Deploy Action'
description: 'Deploy your application to Ploi with Github actions'
author: 'Glennmen'
branding:
  icon: upload-cloud
  color: blue
inputs:
  webhook_url:
    description: 'The Deploy webhook URL'
    required: false
  api_token:
    description: 'Ploi API token'
    required: false
  server_id:
    description: 'Ploi Server ID'
    required: false
  site_id:
    description: 'Ploi Site ID'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    WEBHOOK_URL: ${{ inputs.webhook_url }}
    API_TOKEN: ${{ inputs.api_token }}
    SERVER_ID: ${{ inputs.server_id }}
    SITE_ID: ${{ inputs.site_id }}
